name: ta_ews_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_messaging: 14.7.19
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^16.1.1+1
  flutter_phone_direct_caller: ^2.1.1
  get_it: ^7.6.6
  onesignal_flutter: ^5.1.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 800
    - family: Berlin Sans FB
      fonts:
        - asset: assets/fonts/berlin-sans-fb/BerlinSansFB-Reguler.TTF
        - asset: assets/fonts/berlin-sans-fb/BerlinSansFB-Bold.TTF
          weight: 800
